name: CI-CD Pipeline

on: 
    pull_request:
        branches:
            - master
    push: 
        branches:
            - master

jobs: 
    test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Set up Docker compose
              uses: docker/setup-qemu-action@v2
            
            - name: Ensure Docker Compose is available
              uses: docker-compose version

            - name: Copy .env.example to .env
              run: cp ./integrations/.env.example ./integrations/.env

            - name: Run the tests
              uses: npm run test:integration